package com.example.foodplaner.authuntication.view;

import android.os.Bundle;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.navigation.fragment.NavHostFragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.example.foodplaner.BuildConfig;
import com.example.foodplaner.R;
import com.example.foodplaner.authuntication.presenter.SignupPresenter;
import com.example.foodplaner.model.MealDTO;
import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.Task;
import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import android.content.Intent;
import android.widget.Toast;

/**
 * A simple {@link Fragment} subclass.
 * Use the {@link SignupFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class SignupFragment extends Fragment implements SignupViewInterface{
    TextView signinButton;
    Button signup;
    EditText email;
    EditText password;
    EditText username;
    private SignupPresenter presenter;
    private GoogleSignInClient mGoogleSignInClient;
    private Button btnGoogleSignup; // To reference your XML button

    // 2. ADD: ActivityResultLauncher to handle the Google Intent result
    private final ActivityResultLauncher<Intent> googleSignInLauncher = registerForActivityResult(
            new ActivityResultContracts.StartActivityForResult(),
            result -> {
                if (result.getResultCode() == android.app.Activity.RESULT_OK) {
                    Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(result.getData());
                    try {
                        // Google Sign In was successful, authenticate with Firebase
                        GoogleSignInAccount account = task.getResult(ApiException.class);
                        firebaseAuthWithGoogle(account.getIdToken());
                    } catch (ApiException e) {
                        // Google Sign In failed
                        ShowError("Google sign in failed: " + e.getMessage());
                    }
                }
            }
    );

    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    public SignupFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment SignupFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static SignupFragment newInstance(String param1, String param2) {
        SignupFragment fragment = new SignupFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_signup, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        presenter = new SignupPresenter(this);
        signinButton = view.findViewById(R.id.signin_txt_btn);
        signup = view.findViewById(R.id.btn_signup);
        email = view.findViewById(R.id.email_input_signup);
        password = view.findViewById(R.id.password_input_signup);
        username = view.findViewById(R.id.fullname_input_signup);

        btnGoogleSignup = view.findViewById(R.id.btn_signup_gmail);

        // 4. ADD: Configure Google Sign In
        // R.string.default_web_client_id is auto-generated by google-services.json
        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(BuildConfig.WEB_CLIENT_ID)
                .requestEmail()
                .build();

        mGoogleSignInClient = GoogleSignIn.getClient(requireActivity(), gso);

        // 5. ADD: Set OnClickListener
        btnGoogleSignup.setOnClickListener(v -> {
            Intent signInIntent = mGoogleSignInClient.getSignInIntent();
            googleSignInLauncher.launch(signInIntent);
        });

        signup.setOnClickListener(v -> {
            String emailText = email.getText().toString().trim();
            String passwordText = password.getText().toString().trim();
            String usernameText = username.getText().toString().trim();

            if (emailText.isEmpty() || passwordText.isEmpty()) {
                ShowError("Email and Password cannot be empty");
            } else {
                presenter.RegisterAccountNormally(emailText, passwordText, usernameText);
            }
        });
        signinButton.setOnClickListener(v->{
            NavHostFragment.findNavController(SignupFragment.this)
                    .navigate(R.id.action_signupFragment_to_loginFragment);
        });


    }

    @Override
    public void ShowError(String ErrorMessage) {

    }

    @Override
    public void CorrectCredentials(MealDTO user) {

    }

    @Override
    public void ShowLoading() {

    }

    @Override
    public void HideLoading() {

    }

    @Override
    public void NavigateToHome() {
        NavHostFragment.findNavController(SignupFragment.this)
                .navigate(R.id.action_signupFragment_to_homeFragment);
    }

    @Override
    public void RegisterAccountGoogle(String idToken) {

    }

    // Inside SignupFragment.java
    @Override
    public void onDestroy() {
        super.onDestroy();
        if (presenter != null) {
            presenter.clearDisposables();
        }
    }
    private void firebaseAuthWithGoogle(String idToken) {
        presenter.RegisterAccountGoogle(idToken);
    }
}